import { Recipe } from '@/types';

export const RECIPES: Recipe[] = [
  // ── BREAKFAST ────────────────────────────────────────────────────
  {
    id: 'okayu',
    nameKey: 'recipes.okayuName',
    descriptionKey: 'recipes.okayuDesc',
    benefitKey: 'recipes.okayuBenefit',
    origin: 'Japan',
    flagEmoji: '🇯🇵',
    cuisineRegion: 'asian',
    mealSlot: 'breakfast',
    minAgeMonths: 4,
    allergens: [],
    exclusionTags: [],
    textures: ['puree', 'mashed'],
    nutrition: { kcal: 120, proteinG: 5, carbsG: 20, fatG: 2 },
    substitutions: {},
  },
  {
    id: 'arepas-con-queso',
    nameKey: 'recipes.arepasName',
    descriptionKey: 'recipes.arepasDesc',
    // FIX: was 'recipes.areapasBenefit' (typo)
    benefitKey: 'recipes.arepasBenefit',
    origin: 'Venezuela',
    flagEmoji: '🇻🇪',
    cuisineRegion: 'latinAmerican',
    mealSlot: 'breakfast',
    minAgeMonths: 9,
    allergens: ['dairy'],
    exclusionTags: ['vegan'],
    textures: ['fingerFood', 'soft'],
    nutrition: { kcal: 180, proteinG: 7, carbsG: 28, fatG: 5 },
    substitutions: {
      // FIX: was 'recipes.areapasDairySub' (typo)
      dairy: 'recipes.arepasDairySub',
    },
  },
  {
    id: 'gallo-pinto',
    nameKey: 'recipes.galloName',
    descriptionKey: 'recipes.galloDesc',
    benefitKey: 'recipes.galloBenefit',
    origin: 'Costa Rica',
    flagEmoji: '🇨🇷',
    cuisineRegion: 'latinAmerican',
    mealSlot: 'breakfast',
    minAgeMonths: 6,
    allergens: [],
    exclusionTags: [],
    textures: ['mashed', 'soft'],
    nutrition: { kcal: 160, proteinG: 6, carbsG: 30, fatG: 2 },
    substitutions: {},
  },
  {
    id: 'nhopi-pumpkin-puree',
    nameKey: 'recipes.nhopiName',
    descriptionKey: 'recipes.nhopiDesc',
    benefitKey: 'recipes.nhopiBenefit',
    origin: 'Zimbabwe',
    flagEmoji: '🇿🇼',
    cuisineRegion: 'african',
    mealSlot: 'breakfast',
    minAgeMonths: 4,
    allergens: ['peanuts'],
    exclusionTags: [],
    textures: ['puree', 'mashed'],
    nutrition: { kcal: 130, proteinG: 4, carbsG: 18, fatG: 5 },
    substitutions: {
      peanuts: 'recipes.nhopiPeanutSub',
    },
  },
  {
    id: 'boxty',
    nameKey: 'recipes.boxtyName',
    descriptionKey: 'recipes.boxtyDesc',
    benefitKey: 'recipes.boxtyBenefit',
    origin: 'Ireland',
    flagEmoji: '🇮🇪',
    cuisineRegion: 'european',
    mealSlot: 'breakfast',
    minAgeMonths: 9,
    allergens: [],
    exclusionTags: [],
    textures: ['fingerFood', 'soft'],
    nutrition: { kcal: 150, proteinG: 3, carbsG: 28, fatG: 4 },
    substitutions: {},
  },

  // ── LUNCH ─────────────────────────────────────────────────────────
  {
    id: 'dal-lentil-curry',
    nameKey: 'recipes.dalName',
    descriptionKey: 'recipes.dalDesc',
    benefitKey: 'recipes.dalBenefit',
    origin: 'India',
    flagEmoji: '🇮🇳',
    cuisineRegion: 'asian',
    mealSlot: 'lunch',
    minAgeMonths: 6,
    allergens: [],
    exclusionTags: [],
    textures: ['mashed', 'soft'],
    nutrition: { kcal: 200, proteinG: 9, carbsG: 32, fatG: 4 },
    substitutions: {},
  },
  {
    id: 'koshari',
    nameKey: 'recipes.koshariName',
    descriptionKey: 'recipes.koshariDesc',
    benefitKey: 'recipes.koshariBenefit',
    origin: 'Egypt',
    flagEmoji: '🇪🇬',
    cuisineRegion: 'middleEastern',
    mealSlot: 'lunch',
    minAgeMonths: 9,
    allergens: ['gluten'],
    exclusionTags: [],
    textures: ['soft', 'family'],
    nutrition: { kcal: 250, proteinG: 8, carbsG: 48, fatG: 3 },
    substitutions: {
      gluten: 'recipes.koshariGlutenSub',
    },
  },
  {
    id: 'paella-chicken',
    nameKey: 'recipes.paellaName',
    descriptionKey: 'recipes.paellaDesc',
    benefitKey: 'recipes.paellaBenefit',
    origin: 'Spain',
    flagEmoji: '🇪🇸',
    cuisineRegion: 'mediterranean',
    mealSlot: 'lunch',
    minAgeMonths: 12,
    allergens: [],
    exclusionTags: ['poultry', 'vegetarian', 'vegan'],
    textures: ['soft', 'family'],
    nutrition: { kcal: 270, proteinG: 18, carbsG: 35, fatG: 6 },
    substitutions: {},
  },
  {
    id: 'frikadellen',
    nameKey: 'recipes.frikName',
    descriptionKey: 'recipes.frikDesc',
    benefitKey: 'recipes.frikBenefit',
    origin: 'Germany',
    flagEmoji: '🇩🇪',
    cuisineRegion: 'european',
    mealSlot: 'lunch',
    minAgeMonths: 9,
    allergens: ['gluten', 'eggs'],
    exclusionTags: ['meat', 'vegetarian', 'vegan'],
    textures: ['soft', 'fingerFood'],
    nutrition: { kcal: 230, proteinG: 16, carbsG: 12, fatG: 12 },
    substitutions: {
      gluten: 'recipes.frikGlutenSub',
      eggs: 'recipes.frikEggSub',
    },
  },
  {
    id: 'omurice',
    nameKey: 'recipes.omusiceName',
    descriptionKey: 'recipes.omusiceDesc',
    benefitKey: 'recipes.omusiceBenefit',
    origin: 'Japan',
    flagEmoji: '🇯🇵',
    cuisineRegion: 'asian',
    mealSlot: 'lunch',
    minAgeMonths: 9,
    allergens: ['eggs'],
    exclusionTags: ['vegan'],
    textures: ['soft', 'family'],
    nutrition: { kcal: 220, proteinG: 10, carbsG: 30, fatG: 8 },
    substitutions: {
      eggs: 'recipes.omusiceEggSub',
    },
  },
  {
    id: 'schnitzel',
    nameKey: 'recipes.schnitzelName',
    descriptionKey: 'recipes.schnitzelDesc',
    benefitKey: 'recipes.schnitzelBenefit',
    origin: 'Israel',
    flagEmoji: '🇮🇱',
    cuisineRegion: 'israeli',
    mealSlot: 'lunch',
    minAgeMonths: 12,
    allergens: ['eggs'],
    exclusionTags: ['poultry', 'vegetarian', 'vegan'],
    textures: ['soft', 'fingerFood', 'family'],
    nutrition: { kcal: 260, proteinG: 22, carbsG: 14, fatG: 11 },
    substitutions: {
      eggs: 'recipes.schnitzelEggSub',
    },
  },

  // ── DINNER ────────────────────────────────────────────────────────
  {
    id: 'shakshuka',
    nameKey: 'recipes.shakName',
    descriptionKey: 'recipes.shakDesc',
    benefitKey: 'recipes.shakBenefit',
    origin: 'Israel / North Africa',
    flagEmoji: '🇮🇱',
    cuisineRegion: 'middleEastern',
    mealSlot: 'dinner',
    minAgeMonths: 12,
    allergens: ['eggs'],
    exclusionTags: ['vegan'],
    textures: ['soft', 'family'],
    nutrition: { kcal: 180, proteinG: 10, carbsG: 14, fatG: 9 },
    substitutions: {
      eggs: 'recipes.shakEggSub',
    },
  },
  {
    id: 'sabich-salad',
    nameKey: 'recipes.sabichName',
    descriptionKey: 'recipes.sabichDesc',
    benefitKey: 'recipes.sabichBenefit',
    origin: 'Israel / Iraq',
    flagEmoji: '🇮🇱',
    cuisineRegion: 'middleEastern',
    mealSlot: 'dinner',
    minAgeMonths: 12,
    allergens: ['eggs', 'sesame'],
    exclusionTags: ['vegan'],
    textures: ['soft', 'family'],
    nutrition: { kcal: 200, proteinG: 9, carbsG: 16, fatG: 12 },
    substitutions: {
      eggs: 'recipes.sabichEggSub',
      sesame: 'recipes.sabichSesameSub',
    },
  },
  {
    id: 'hummus',
    nameKey: 'recipes.hummusName',
    descriptionKey: 'recipes.hummusDesc',
    benefitKey: 'recipes.hummusBenefit',
    origin: 'Middle East',
    flagEmoji: '🫘',
    cuisineRegion: 'middleEastern',
    mealSlot: 'dinner',
    minAgeMonths: 9,
    allergens: ['sesame'],
    exclusionTags: [],
    textures: ['puree', 'mashed'],
    nutrition: { kcal: 160, proteinG: 8, carbsG: 18, fatG: 7 },
    substitutions: {
      sesame: 'recipes.hummusSesameSub',
    },
  },
  {
    id: 'greek-salad-feta',
    nameKey: 'recipes.greekName',
    descriptionKey: 'recipes.greekDesc',
    benefitKey: 'recipes.greekBenefit',
    origin: 'Greece',
    flagEmoji: '🇬🇷',
    cuisineRegion: 'mediterranean',
    mealSlot: 'dinner',
    minAgeMonths: 12,
    allergens: ['dairy'],
    exclusionTags: ['vegan'],
    textures: ['soft', 'family'],
    nutrition: { kcal: 150, proteinG: 6, carbsG: 10, fatG: 10 },
    substitutions: {
      dairy: 'recipes.greekDairySub',
    },
  },
  {
    id: 'sweet-potato-bean-puree',
    nameKey: 'recipes.sweetPotatoName',
    descriptionKey: 'recipes.sweetPotatoDesc',
    benefitKey: 'recipes.sweetPotatoBenefit',
    origin: 'Mexico',
    flagEmoji: '🇲🇽',
    cuisineRegion: 'latinAmerican',
    mealSlot: 'dinner',
    minAgeMonths: 4,
    allergens: [],
    exclusionTags: [],
    textures: ['puree', 'mashed'],
    nutrition: { kcal: 140, proteinG: 5, carbsG: 26, fatG: 2 },
    substitutions: {},
  },
  {
    id: 'ptitim-vegetables',
    nameKey: 'recipes.ptitimName',
    descriptionKey: 'recipes.ptitimDesc',
    benefitKey: 'recipes.ptitimBenefit',
    origin: 'Israel',
    flagEmoji: '🇮🇱',
    cuisineRegion: 'israeli',
    mealSlot: 'dinner',
    minAgeMonths: 9,
    allergens: ['gluten'],
    exclusionTags: [],
    textures: ['soft', 'family'],
    nutrition: { kcal: 175, proteinG: 5, carbsG: 32, fatG: 4 },
    substitutions: {
      gluten: 'recipes.ptitimGlutenSub',
    },
  },
];

// Guaranteed allergen-free, exclusion-free fallback per slot
export const FALLBACK_RECIPES: Record<string, Recipe> = {
  breakfast: RECIPES.find(r => r.id === 'okayu')!,
  lunch: RECIPES.find(r => r.id === 'dal-lentil-curry')!,
  dinner: RECIPES.find(r => r.id === 'sweet-potato-bean-puree')!,
};
